### ISSUE TITLE
Exception thrown while trying to add policy using Cosmos DB

### ISSUE THREAD

**Issue by johnmillard-ra** [casbin-net/efcore-adapter#45]
Hello!

First, I apologize if I've overlooked something in the examples or elsewhere, though I spent the better part of yesterday looking. Starting with the example in the readme, I've modified it to use Cosmos:

```c#
let options = DbContextOptionsBuilder<CasbinDbContext<int>>()
                      .UseCosmos("https://localhost:8081", "key","CasbinAuthorizationDB")
                      .Options

let context = new CasbinDbContext<int>(options)
let! _ = context.Database.EnsureCreatedAsync () |> Async.AwaitTask

let model = Model.CreateDefaultFromFile "examples/rbac_model.conf"
let efCoreAdapter = EFCoreAdapter<int>(context);
let e = Enforcer(model, efCoreAdapter);

```

This works correctly, in that I end up with a database and container. However, this next bit fails:

```
let! result = e.AddPolicyAsync ("alice", "data1", "admin") |> Async.AwaitTask
```

And it throws this:

`The property 'CasbinRule<int>.Id' does not have a value set and no value generator is available for properties of type 'int'. Either set a value for the property before adding the entity or configure a value generator for properties of type 'int' in 'OnModelCreating'.`

I can see from poking around some of the EF (which I am utterly unfamiliar with) and Cosmos documentation that *something* ought be generating the IDs - however, I assumed the adapter would do that, as it's providing the class (CasbinRule) to use.

Am I wrong in my assumptions? And can anyone suggest how to resolve this?

Thanks!
John

**Comment by johnmillard-ra** [comment]
To add a bit more context: things blow up in EFCoreAdapter.AddPolicyAsync() while calling CasbinRules.AddAsync().

Here's the call stack:

```
System.NotSupportedException: The property 'CasbinRule<int>.Id' does not have a value set and no value generator is available for properties of type 'int'. Either set a value for the property before adding the entity or configure a value generator for properties of type 'int' in 'OnModelCreating'.
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorSelector.Create(IProperty property, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Cosmos.ValueGeneration.Internal.CosmosValueGeneratorSelector.Create(IProperty property, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorSelector.<Select>b__6_0(IProperty p, IEntityType t)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorCache.<>c.<GetOrAdd>b__3_0(CacheKey ck)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorCache.GetOrAdd(IProperty property, IEntityType entityType, Func`3 factory)
   at Microsoft.EntityFrameworkCore.ValueGeneration.ValueGeneratorSelector.Select(IProperty property, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ValueGenerationManager.GetValueGenerator(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ValueGenerationManager.GenerateAsync(InternalEntityEntry entry, Boolean includePrimaryKey, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityStateAsync(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintActionAsync(EntityEntryGraphNode`1 node, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraphAsync[TState](EntityEntryGraphNode`1 node, Func`3 handleNode, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddAsync(TEntity entity, CancellationToken cancellationToken)
   at Casbin.Adapter.EFCore.EFCoreAdapter`3.AddPolicyAsync(String section, String policyType, IList`1 rule)
```

**Comment by Sagilio** [comment]
Many DBs can auto-generating the int primary key, so EFCore Adapter will not set the Id property when adding policy. But cosmos DB may not auto-generating it.

```csharp
public class MyEFCoreAdapter : EFCoreAdapter<int>
{
    public MyEFCoreAdapter(CasbinDbContext<int> casbinDbContext) 
        : base(casbinDbContext)
    {
    }

    // This method will be called before calling `DbCotnext.CasbinRules.Add(casbinRule);`
    protected override CasbinRule<int> OnAddPolicy(string section, string policyType, IEnumerable<string> rule, CasbinRule<int> casbinRule)
    {
        // Generating and set the Id property.
        casbinRule.Id = 1;         
        return base.OnAddPolicy(section, policyType, rule, casbinRule);
    }
}
```

**Comment by johnmillard-ra** [comment]
Thanks!

**Comment by hsluoyz** [comment]
@Sagilio can we support this natively inside our adapter? Like if Cosmos DB is used, then the EFCore Adapter set the Id property.

**Comment by johnmillard-ra** [comment]
Btw, I ended up temporarily generating a new guid for the id on each create, and that works fine (adding, removing, checking, etc.) - I may generate a hash instead based on key aspects of the policy, but I'm not sure it matters.

**Comment by j-schuma** [comment]
Hi @johnmillard-ra, how did you end up solving this. I was trying to use GUIDs for Ids generated in the MyEFCoreAdapter but something wants the id to be a string. Probably missing something. :)

**Comment by j-schuma** [comment]
Nevermind, I am silly and just missed to modify a generic. :) But you also used GUIDs, right?

**Comment by hsluoyz** [comment]
Closed as resolved
