### ISSUE TITLE
Cannot be used with Casbin.NET package > 2.1.1

### ISSUE THREAD

**Issue by dgg** [casbin-net/efcore-adapter#70]
Hi, we are evaluating casbin for a .NET project that we are starting out.

We want to store policies in a database (thinking about postgres) and using `Casbin.NET.Adapter.EFCore v2.1.0` and `Npgsql.EntityFrameworkCore.PostgreSQL v8.0.2`.

If we are a version of the package `Casbin.NET` higher that `2.1.1` we get the following exception:

```
System.EntryPointNotFoundException: Entry point was not found.
         at System.Collections.Generic.IReadOnlyCollection`1.get_Count()
         at Casbin.Persist.Adapter.EFCore.EFCoreAdapter`3.AddPolicyAsync(String section, String policyType, IPolicyValues values)
         at Casbin.Model.DefaultPolicyManager.AddPolicyAsync(IPolicyValues rule)
         at Casbin.InternalEnforcerExtension.InternalAddPolicyAsync(IEnforcer enforcer, String section, String policyType, IPolicyValues values)
```

Of course we can evaluate the solution with a 5 month-old version, but that would be a showstopper to continue with casbin.

I am not sure what could be the solution for this problem.

Thanks for your help.

**Comment by hsluoyz** [comment]
@huazhikui @sagilio
